# Sidebar menu
menu:
  home: /
  msg: /msg
  about: /about
  # links: /links

# Profile
profile:
  # avatar: /avatar.jpg
  # Email address will be used for showing gravatar(https://en.gravatar.com) avatar if `avatar` is not specified.
  email: jiajixu@qq.com
  bio: 很多人都说：我不知道我自己想要什么。其实这句话的真正含义是：我没有勇气面对和足够的努力去争取我想要的。

# Social media
sns:
  github: https://github.com/xujiaji
  # twitter: https://twitter.com/yourname
  # gplus: https://plus.google.com/u/0/xxx
  weibo: https://weibo.com/jiajixu

footer:
  # If not defined, will show current year and author, eg: ©2018 • Superman
  copyright: ©2018 • xujiaji

  # Set to false to hide Hexo link.
  powered: true
  # Set to false to hide theme info.
  theme: true

  # Custom text can be defined here.
  # custom: Hosted by <a target="_blank" rel="external nofollow" href="https://pages.coding.me"><b>Coding Pages</b></a>

# Post
post:
  # Table of content
  # Set to false to disable
  toc:
    # The depth of toc, default is 2, maximum to 4.
    depth: 4
    # Showing index before toc, eg. 1.1 title
    index: true

# Disqus comments
disqus:
  shortname: xujiaji
  # Set to true to auto load disqus, otherwise will display a button
  autoload: true

# Assets path
assets:
  # prefix: 'https://cdn.example.com'
  # suffix: '?m=webp&q=80'

# Web App Manifest
manifest:
  short_name: XBlog
  name: 徐佳吉的博客
  start_url: /
  theme_color: '#ffffcc'
  background_color: '#ffffcc'
  icons:
    - src: image/icon-194x194.png
      sizes: 194x194 512x512
      type: image/png
    - src: image/icon-144x144.png
      sizes: 144x144
      type: image/png

### Pagination size
# The amount of posts displayed on a single archive/tag/category page, default is `10`, set to `0` to disable pagination.
archive:
  per_page: 10
tag:
  per_page: 10
category:
  per_page: 10

# Google analytics
ga: UA-117088783-1
